title: Matt's Blog
description: My space to share what I'm working on.
author: Matt Krause
avatar: Logo(blackBG).png
#email: 
skin: daylight

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: Logo(blackBG).png
social:
  name: Matt Krause
  links:
    - https://hachyderm.io/@mattckrause
    - https://www.linkedin.com/matthew-krause
    - https://github.com/mattckrause
#google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
